export default {
  SIZES: {
    XS: 'XS',
    MD: 'MD',
    LG: 'LG',
  },
  DEFAULT_COLOR_CHECK_BOX: '#03a7d5',
  DISCOUNT_TYPE: {
    GROWING: 'Растущая',
    FALLING: 'Падающая',
  },
  QUESTION_TYPE: {
    CHECK_BOX_TEXT_VARIANTS: 'CHECK_BOX_TEXT_VARIANTS',
    CHECK_BOX_TEXT_AND_IMAGE_VARIANTS: 'CHECK_BOX_TEXT_AND_IMAGE_VARIANTS',
    RADIO_BOX_TEXT_AND_IMAGE_VARIANTS: 'RADIO_BOX_TEXT_AND_IMAGE_VARIANTS',
    RADIO_BOX_TEXT_VARIANTS: 'RADIO_BOX_TEXT_VARIANTS',
    RADIO_BOX_SWIPER_SLIDER: 'RADIO_BOX_SWIPER_SLIDER',
    TEXT_VARIANT: 'TEXT_VARIANT',
    COMBO_BOX_VARIANTS: 'COMBO_BOX_VARIANTS',
    DATE_PICKER_VARIANTS: 'DATE_PICKER_VARIANTS',
    RANGE_VARIANTS: 'RANGE_VARIANTS',
    FILE_VARIANTS: 'FILE_VARIANTS',
    QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  },
}
