export default {
  QUESTION_TYPE: {
    CHECK_BOX_TEXT_VARIANTS: 'CHECK_BOX_TEXT_VARIANTS',
    RADIO_BOX_TEXT_VARIANTS: 'RADIO_BOX_TEXT_VARIANTS',
    COMBO_BOX_VARIANTS: 'COMBO_BOX_VARIANTS',
    DATE_PICKER_VARIANTS: 'DATE_PICKER_VARIANTS',
    RADIO_BOX_SWIPER_SLIDER: 'RADIO_BOX_SWIPER_SLIDER',
    QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  },
}
