export default {
  id: 1,
  widget_id: null,
  data: {
    step1: {
      title: '',
      subtite: '',
      button_text: '',
    },
    step2: [
      {
        variants: [
          {
            id: 1,
            text: 'Вариант 1',
          },
          {
            id: 2,
            text: 'Вариант 2',
          },
          {
            id: 3,
            text: 'Вариант 3',
          },
          {
            id: 4,
            text: 'Вариант 4',
          },
        ],
        tip_oprosa: 'var-otvetov',
        optional: true,
        diapazon_polzunka: false,
        neskolko: true,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: true,
        question: 'Вопрос 1',
        massage: 'Здесь будет сообщение от оператора.',
      },
      {
        variants: [
          {
            id: 1,
            text: 'Вариант 1',
          },
          {
            id: 2,
            text: 'Вариант 2',
          },
          {
            id: 3,
            text: 'Вариант 3',
          },
          {
            id: 4,
            text: 'Вариант 4',
          },
        ],
        tip_oprosa: 'var-otvetov',
        optional: true,
        diapazon_polzunka: true,
        neskolko: false,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос',
        massage: 'Здесь будет сообщение от оператора!',
      },
      {
        variants: [
          {
            id: 1,
            text: 'Ответ 1',
            src: '',
          },
          {
            id: 2,
            text: 'Ответ 2',
            src: '',
          },
          {
            id: 3,
            text: 'Ответ 3',
            src: '',
          },
          {
            id: 4,
            text: 'Ответ 4',
            src: '',
          },
        ],
        tip_oprosa: 'var-s-kartinami',
        optional: true,
        diapazon_polzunka: true,
        neskolko: true,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос с картинками',
        massage: 'Здесь будет вопрос Здесь будет вопрос Здесь будет вопрос',
      },
      {
        variants: [
          {
            id: 1,
            text: 'Вариант 1',
            src: '',
          },
          {
            id: 2,
            text: 'Вариант 2',
            src: '',
          },
          {
            id: 3,
            text: 'Еще Вариант',
            src: '',
          },
          {
            id: 4,
            text: 'И еще',
            src: '',
          },
        ],
        tip_oprosa: 'var-i-kartinka',
        optional: true,
        diapazon_polzunka: true,
        neskolko: true,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет текст вопроса',
        massage: 'Привет!',
      },
      {
        variants: [
          {
            id: 1,
            text: 'Вариант 1',
            src: '',
          },
          {
            id: 2,
            text: 'Вариант 2',
            src: '',
          },
          {
            id: 3,
            text: 'Вариант 3',
            src: '',
          },
          {
            id: 4,
            text: 'Вариант 4',
            src: '',
          },
        ],
        tip_oprosa: 'var-i-kartinka',
        optional: true,
        diapazon_polzunka: true,
        neskolko: false,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос',
        massage: 'Привет!',
      },
      {
        variants: [],
        tip_oprosa: 'pole-dlya-vvoda',
        optional: true,
        diapazon_polzunka: true,
        neskolko: true,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос',
        massage: 'Напиши произвольный ответ',
        primer_otveta: '',
      },
      {
        variants: [
          {
            id: 1,
            text: 'Вариант2',
          },
          {
            id: 2,
            text: 'Вариант 3',
          },
          {
            id: 3,
            text: 'Вариант 4',
          },
        ],
        tip_oprosa: 'vipadayshii-spisok',
        optional: true,
        diapazon_polzunka: true,
        neskolko: true,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос со списком',
        massage: 'Выбери вариант из списка',
        primer_otveta: 'Вариант 1',
      },
      {
        variants: [],
        tip_oprosa: 'data',
        optional: true,
        diapazon_polzunka: true,
        neskolko: true,
        vibor_diapazon_dat: true,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос с датой',
        massage: 'Выберите дату',
      },
      {
        variants: [],
        tip_oprosa: 'polzynok',
        optional: true,
        diapazon_polzunka: true,
        neskolko: true,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос с ползунком',
        massage: 'Здесь будет вопрос Здесь будет вопрос Здесь будет вопрос',
        diapazon_dat_ot: '1',
        diapazon_dat_do: '150',
        diapazon_dat_step: '1',
      },
      {
        variants: [
          {
            type_files: 'all',
            checked: true,
          },
        ],
        tip_oprosa: 'time-page',
        optional: true,
        diapazon_polzunka: true,
        neskolko: true,
        vibor_diapazon_dat: false,
        vibor_vremeni: false,
        neobbyazatelnii_vopros: false,
        question: 'Здесь будет вопрос с фалом ',
        massage: 'Здесь будет вопрос Здесь будет вопрос',
      },
    ],
    step3: {
      konsultant: {
        name: 'Андрей',
        dolgnost: 'Консультант',
        is_checked: true,
      },
      motivaciya: {
        'type-skidki': 'Падающая',
        prise1: '1000',
        prise2: '500',
        is_checked: true,
      },
      bonus: {
        first: {
          type: 'prais',
          name: 'Полное руковоство для бизнеса',
          color: '#AFD4FF',
          first: true,
          finish: true,
        },
        finish: {
          active: true,
          type: 'kupon',
          name: 'Скидка на месяц подписки',
          color: '#EFA9FF',
          first: true,
          finish: false,
        },
      },
    },
    step4: {
      name: {
        active: true,
        value: '',
      },
      email: {
        active: false,
        value: '',
      },
      phone: {
        active: true,
        value: '',
      },
      comment: {
        active: false,
        value: '',
      },
      send: false,
      title_massenger: '',
      text_button_massenger: '',
      title: '',
      text: '',
      text_button: '',
      messenge: '',
    },
    step5: {
      color: '#1c2eb5',
      linck: '',
      event: '',
      'text-label': '',
      active: 'Подключите виджет к своей кнопке',
      icon: '/global_assets/images/icon_kviz/design/form.svg',
      position: 'down-right',
    },
  },
  created_at: '2021-03-29 00:00:00',
  updated_at: '2021-03-29 00:00:00',
}
