export default {
  // ACTION
  NEXT_QUESTION_ACTION: 'NEXT_QUESTION_ACTION',
  PREV_QUESTION_ACTION: 'PREV_QUESTION_ACTION',
  FETCH_QUIZ_CONFIG_ACTION: 'FETCH_QUIZ_CONFIG_ACTION',
  FETCH_QUIZ_CONFIG_SHORT_ACTION: 'FETCH_QUIZ_CONFIG_SHORT_ACTION',
  SAVE_STEP_ANSWER_ACTION: 'SAVE_STEP_ANSWER_ACTION',
  LOAD_DOC_ACTION: 'LOAD_DOC_ACTION',
  SAVE_RESULT_QUIZ_ACTION: 'SAVE_RESULT_QUIZ_ACTION',
  GET_QUIZ_PARAMS_BY_SHORT_URL_ACTION: 'GET_QUIZ_PARAMS_BY_SHORT_URL_ACTION',
  // MUTATION
  SET_QUIZ_ID: 'SET_QUIZ_ID',
  SET_METRIKA_ID: 'SET_METRIKA_ID',
  SET_NEIROS_VISIT: 'SET_NEIROS_VISIT',
  SET_SESSION_ID: 'SET_SESSION_ID',
  SET_QUIZ_STEPS: 'SET_QUIZ_STEPS',
  SET_CURRENT_QUESTION: 'SET_CURRENT_QUESTION',
  SAVE_STEP_ANSWER: 'SAVE_STEP_ANSWER',
  SET_APP_SIZE: 'SET_APP_SIZE',
}
