export default {
  // ACTION
  NEXT_QUESTION_ACTION: 'NEXT_QUESTION_ACTION',
  PREV_QUESTION_ACTION: 'PREV_QUESTION_ACTION',
  // MUTATION
  SET_QUIZ_ID: 'SET_QUIZ_ID',
  SET_CURRENT_QUESTION: 'SET_CURRENT_QUESTION',
}
